In [81]:
import pandas as pd
import numpy as np
import math

In [6]:
df = pd.read_csv('data.csv')

In [18]:
ROLL_NUMBER_LIST = {'2k17/mc/'+ str(i) : False for i in range(1,127)}
# print(ROLL_NUMBER_LIST)

In [85]:
# names in CSV file for the corresponding coloumn 

_partner1 = 'ROLL NUMBER - STUDENT 1'
_partner2 = 'ROLL NUMBER - STUDENT 2'

def remove_anamoly(param):
    ret_val = []
    for student in df[param]:
        if student is not None and type(student) == str and student[8] == '0':
            student = student[:8] + student[9:]
            student = student.replace(' ','')
            student = student.replace('DTU/','')
            student = student.lower()
            student = student.replace('e','')
        ret_val.append(student)
    return ret_val

df[_partner1] = remove_anamoly(_partner1)
df[_partner2] = remove_anamoly(_partner2)

for student in df[_partner1]:
    print(student)
    if type(student) == str and student is not None and student != '':
        ROLL_NUMBER_LIST[student] = True

for student in df[_partner2]:
    print(student)
    if type(student) == str and student is not None and student != '':
        ROLL_NUMBER_LIST[student.lower()] = True

nan
2k17/mc/2
2K17/MC/122
2K17/MC/89
2K17/MC/27
2k17/MC/76
2k17/mc/33
2K17/MC/110
nan
2k17/mc/28
2k17/mc/60
2k17/mc/81
2K17/MC/113
2K17/MC/52
2k17/mc/9
2kq7/mc/57
2k17/mc/78
2K17/MC/48
2k17/mc/116
2K17/MC/101
2k17/mc/69
2K17/MC/117
2K17/MC/75
2K17/MC/109
2k17/MC/56
2K17/MC/88
2K17/MC/49
2k17/MC/106
2k17/mc/79
2k17/mc/96
2k17/mc/83
2k17/mc/43
2k17/mc/20
2k17/mc/16
nan
2k17/mc073
2K17/MC/126
2k17/mc/120
2K17/MC/80
nan
2K17/MC/15
2K17/MC/124
2K17/MC/97
2k17/mc/50
2K17/MC/108
2k17/MC/108
2K17/MC/71
2K17/MC/115
2k17/mc/4
2K17/MCE/093
nan
2k17/mc/45
2k17/mc/6
2k17/mc/82
nan
nan
2K17/MC/121
2K17/MC/103
2k17/MC/77
2k17/mc/92
2k17/mc/7
2k17/mc/31
2k17/MC/53
2k17/mc/46
2k17/mc/62
2K17/MC/29
2k17/mc/25
2K17/MC/95
2k17/mc/41
2k17/mc/23
nan
2k17/mc/02
2K17/MC/122
2K17/MC/89
2K17/MC/27
2k17/MC/76
2k17/mc/33
2K17/MC/110
nan
2k17/mc/28
2k17/mc/60
2k17/mc/81
2K17/MC/113
2K17/MC/52
2k17/mc/9
2kq7/mc/57
2k17/mc/78
2K17/MC/48
2k17/mc/116
2K17/MC/101
2k17/mc/69
2K17/MC/117
2K17/MC/75
2K17/MC/109
2k17/MC/56
2K17/MC/88
2K17/MC/49
2k17/MC/106
2k17/mc/79
2k17/mc/96
2k17/mc/83
2k17/mc/43
2k17/mc/20
2k17/mc/16
nan
2k17/mc073
2K17/MC/126
2k17/mc/120
2K17/MC/80
nan
2K17/MC/15
2K17/MC/124
2K17/MC/97
2k17/mc/50
2K17/MC/108
2k17/MC/108
2K17/MC/71
2K17/MC/115
2k17/mc/04
2K17/MCE/093
nan
2k17/mc/45
2k17/mc/6
2k17/mc/82
nan
nan
2K17/MC/121
2K17/MC/103
2k17/MC/77
2k17/mc/92
2k17/mc/07
2k17/mc/31
2k17/MC/53
2k17/mc/46
2k17/mc/62
2K17/MC/29
2k17/mc/25
2K17/MC/95
2k17/mc/41
2k17/mc/23

In [76]:
not_filled_list = [student for student in ROLL_NUMBER_LIST if ROLL_NUMBER_LIST[student] == False ]
# print(not_filled_list)